# Generated by Django 2.0.2 on 2018-02-14 14:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, default='', max_length=250, verbose_name='H1')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='<title>')),
                ('description', models.TextField(blank=True, default='', verbose_name='<meta name="description">')),
                ('keywords', models.TextField(blank=True, default='', verbose_name='<meta name="keywords">')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('slug', models.SlugField()),
                ('anons', models.TextField(blank=True, default='', verbose_name='Анонс')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Заголовок')),
                ('h1', models.CharField(blank=True, default='', max_length=250, verbose_name='H1')),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tags'),
        ),
    ]
