
# Generated by Django 1.11.7 on 2017-12-06 14:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='<title>')),
                ('description', models.TextField(blank=True, default='', verbose_name='<meta name="description">')),
                ('keywords', models.TextField(blank=True, default='', verbose_name='<meta name="keywords">')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('h1', models.CharField(blank=True, default='', max_length=250, verbose_name='H1')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('url', models.SlugField(help_text='/about/test/test2', max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('(?:[/?#][^\\s]*)?', 32), 'Введите правильный url, без указания схемы и домена', 'invalid')], verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='<title>')),
                ('description', models.TextField(blank=True, default='', verbose_name='<meta name="description">')),
                ('keywords', models.TextField(blank=True, default='', verbose_name='<meta name="keywords">')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('h1', models.CharField(blank=True, default='', max_length=250, verbose_name='H1')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('anons', models.TextField(blank=True, default='', verbose_name='Анонс')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Заголовок')),
                ('h1', models.CharField(blank=True, default='', max_length=250, verbose_name='H1')),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, to='text_pages.Tags'),
        ),
    ]
