# Generated by Django 2.0.2 on 2018-02-14 11:44

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='url',
            field=models.CharField(help_text='/about/test/test2', max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\/(?:[/?#]?[^\\s]*)[^\\/]$'), 'Введите правильный url, без указания схемы и домена', 'invalid')], verbose_name='URL'),
        ),
    ]
