# Generated by Django 2.0.2 on 2018-02-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0002_auto_20180214_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
