# Generated by Django 2.0.6 on 2018-07-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0004_auto_20180214_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ('-created',), 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
