# Generated by Django 2.0.2 on 2018-03-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faq.Subject', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='h1',
            field=models.CharField(max_length=250, verbose_name='H1'),
        ),
    ]
