# Generated by Django 2.0.3 on 2018-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20180302_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('-order',), 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0, help_text='Меньше первее'),
        ),
    ]
