# Generated by Django 2.0.3 on 2018-04-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20180322_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('subject__order', 'order'), 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('order',), 'verbose_name': 'тема помощи', 'verbose_name_plural': 'темы помощи'},
        ),
    ]
